spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: derich.rosario22@gmail.com
    password: nubq otub srtl dauy
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  application:
    name: Cliente  # Nome do microsserviço
    mongodb:
      database: cliente  # Banco de dados MongoDB do microsserviço
      uri: mongodb://mongo-cliente:27017/cliente
  cloud:
    zookeeper:
      connect-string: zookeeper:2181  # Endereço do Zookeeper
      discovery:
        enabled: true  # Habilita o registro do serviço
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
server:
  port: 8081  # Porta do microsserviço

