spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: derich.rosario22@gmail.com
    password: nubq otub srtl dauy
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  application:
    name: Cliente  # Nome do microsserviço
    mongodb:
      database: cliente  # Banco de dados MongoDB do microsserviço
      uri: mongodb://ecommerce-mongo-database:27018/cliente
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
server:
  port: 8081  # Porta do microsserviço

eureka:
  client:
    service-url:
      defaultZone: http://service-discovery:8761/eureka/
