spring:
#  rabbitmq:
#    host: rabbitmq
#    port: 5672
#    username: guest
#    password: guest
  application:
    name: Produto  # Nome do microsserviço
    mongodb:
      database: produto  # Banco de dados MongoDB do microsserviço
      uri: mongodb://ecommerce-mongo-database:27018/produto
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
server:
  port: 8082 # Porta do microsserviço

eureka:
  client:
    service-url:
      defaultZone: http://service-discovery:8761/eureka/
