spring:
  application:
    name: Produto  # Nome do microsserviço
    mongodb:
      database: produto  # Banco de dados MongoDB do microsserviço
      uri: mongodb://mongo-cliente:27017/produto
  cloud:
    zookeeper:
      connect-string: zookeeper:2181  # Endereço do Zookeeper
      discovery:
        enabled: true  # Habilita o registro do serviço
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
server:
  port: 8082  # Porta do microsserviço