spring:
#  rabbitmq:
#    host: rabbitmq
#    port: 5672
#    username: guest
#    password: guest
  mail:
    host: smtp.gmail.com
    port: 587
    username: derich.rosario22@gmail.com
    password: ${password}
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true
  application:
    name: Venda  # Nome do microsserviço
    mongodb:
      database: venda  # Banco de dados MongoDB do microsserviço
      uri: ${mongoDBUrl}
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

server:
  port: 8083 # Porta do microsserviço

eureka:
  client:
    service-url:
      defaultZone: http://service-discovery:8761/eureka/

mercadopago:
  access:
    token: ${tokenMP}

melhorenvio:
  token: ${tokenME}
  email:
    contato: ${emailContato}
