spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
  application:
    name: Venda  # Nome do microsserviço
    mongodb:
      database: venda  # Banco de dados MongoDB do microsserviço
      uri: mongodb://ecommerce-mongo-database:27018/venda
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
server:
  port: 8083 # Porta do microsserviço

eureka:
  client:
    service-url:
      defaultZone: http://service-discovery:8761/eureka/

mercadopago:
  access:
    token: TEST-8948901045439209-020514-aca24c9fe05d35a793925d4cf8633506-751468139
