spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  application:
    name: Venda  # Nome do microsserviço
    mongodb:
      database: venda  # Banco de dados MongoDB do microsserviço
      uri: mongodb://mongo-cliente:27017/venda
  cloud:
    zookeeper:
      connect-string: zookeeper:2181  # Endereço do Zookeeper
      discovery:
        enabled: true  # Habilita o registro do serviço
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
server:
  port: 8083 # Porta do microsserviço