networks:
  ecommerce-net:
    name: ecommerce-net
    driver: bridge

services:
  service-discovery:
    image: service-discovery
    pull_policy: never
    container_name: "ecommerce-service-discovery"
    networks:
      - ecommerce-net
    ports:
      - "8761:8761"

  ecommerce-mongo-database:
    image: mongo:latest
    container_name: "ecommerce-database"
    networks:
      - ecommerce-net
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db  # Volume persistente

#  rabbitmq:
#    image: rabbitmq:3-management
#    container_name: "ecommerce-rabbitmq"
#    networks:
#      - ecommerce-net
#    ports:
#      - "5672:5672"    # Porta de comunicação dos clientes RabbitMQ
#      - "15672:15672"  # Porta para a interface de gerenciamento

  frontend:
    build:
      context: ../Front-End/ecommerce
    container_name: ecommerce-frontend
    networks:
      - ecommerce-net
    ports:
      - "80:80"  # A aplicação será servida na porta 80

  cliente:
    image: cliente
    pull_policy: never
    container_name: "ecommerce-cliente"
    environment:
      - spring.data.mongodb.uri=mongodb://ecommerce-mongo-database:27017/cliente
      - PORT=8081
      - DISCOVERY_HOST=service-discovery
#      - RABBITMQ_HOST=rabbitmq
#      - RABBITMQ_PORT=5672
    networks:
      - ecommerce-net
    ports:
      - "8081:8081"
    depends_on:
      - service-discovery
      - ecommerce-mongo-database
#      - rabbitmq

  produto:
    image: produto
    pull_policy: never
    container_name: "ecommerce-produto"
    environment:
      - spring.data.mongodb.uri=mongodb://ecommerce-mongo-database:27017/produto
      - PORT=8082
      - DISCOVERY_HOST=service-discovery
#      - RABBITMQ_HOST=rabbitmq
#      - RABBITMQ_PORT=5672
    networks:
      - ecommerce-net
    ports:
      - "8082:8082"
    depends_on:
      - service-discovery
      - ecommerce-mongo-database
#      - rabbitmq


  venda:
    image: venda
    pull_policy: never
    container_name: "ecommerce-venda"
    environment:
      - spring.data.mongodb.uri=mongodb://ecommerce-mongo-database:27017/venda
      - PORT=8083
      - DISCOVERY_HOST=service-discovery
#      - RABBITMQ_HOST=rabbitmq
#      - RABBITMQ_PORT=5672
    networks:
      - ecommerce-net
    ports:
      - "8083:8083"
    depends_on:
      - service-discovery
      - ecommerce-mongo-database
#      - rabbitmq

volumes:
  mongo_data:
