networks:
  ecommerce-net:
    name: ecommerce-net
    driver: bridge

services:
  service-discovery:
    image: service-discovery
    pull_policy: never
    container_name: "ecommerce-service-discovery"
    networks:
      - ecommerce-net
    ports:
      - "8761:8761"

  ecommerce-mongo-database:
    image: mongo:latest
    container_name: "ecommerce-database"
    networks:
      - ecommerce-net
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db  # Volume persistente

  frontend:
    build:
      context: ../Front-End/ecommerce
    container_name: ecommerce-frontend
    networks:
      - ecommerce-net
    ports:
      - "80:80"  # A aplicação será servida na porta 80
    env_file:
      - .env

  cliente:
    image: cliente
    pull_policy: never
    container_name: "ecommerce-cliente"
    environment:
      - spring.data.mongodb.uri=${mongoDBCliente}
      - PORT=8081
      - DISCOVERY_HOST=service-discovery
    networks:
      - ecommerce-net
    ports:
      - "8081:8081"
    env_file:
      - .env
    depends_on:
      - service-discovery
      - ecommerce-mongo-database

  produto:
    image: produto
    pull_policy: never
    container_name: "ecommerce-produto"
    environment:
      - spring.data.mongodb.uri=${mongoDBProduto}
      - PORT=8082
      - DISCOVERY_HOST=service-discovery
    networks:
      - ecommerce-net
    ports:
      - "8082:8082"
    env_file:
      - .env
    depends_on:
      - service-discovery
      - ecommerce-mongo-database

  venda:
    image: venda
    pull_policy: never
    container_name: "ecommerce-venda"
    environment:
      - spring.data.mongodb.uri=${mongoDBVenda}
      - PORT=8083
      - DISCOVERY_HOST=service-discovery
    networks:
      - ecommerce-net
    ports:
      - "8083:8083"
    env_file:
      - .env
    depends_on:
      - service-discovery
      - ecommerce-mongo-database

volumes:
  mongo_data:
